USE sakila;

# Challenge - Joining on multiple tables
# Write SQL queries to perform the following tasks using the Sakila database:

# 1. List the number of films per category.

SELECT c.name AS category_name, COUNT(fc.film_id) AS count_films
FROM film_category AS fc
INNER JOIN category AS c 
ON fc.category_id = c.category_id
GROUP BY c.name;

# 2. Retrieve the store ID, city, and country for each store.

SELECT store.store_id, city.city, country.country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id);

# 3. Calculate the total revenue generated by each store in dollars.

SELECT staff.store_id, SUM(payment.amount) AS total_revenue
FROM staff
INNER JOIN payment
USING (staff_id)
GROUP BY staff.store_id;

# 4. Determine the average running time of films for each category

SELECT category.name, AVG(film.length) AS avg_running_time
FROM film
INNER JOIN film_category
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY category.name



